services:
  telegram_extract_db:
    image: postgres:15
    container_name: cuban-jobs-db
    restart: always
    ports:
      - "4000:5432"  # Mapea el puerto 5432 del contenedor al puerto 5433 del host
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       # Variables de entorno para la configuración de PostgreSQL
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - telegram_extract_db_data:/var/lib/postgresql/data  # Persistencia de los datos

volumes:
  telegram_extract_db_data: # Define un volumen con nombre